# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panditprofile',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
